apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchExpressions:
            - key: environment
              operator: In
              values:
                - vcteam-b
  template:
    metadata:
      name: '{{name}}-cert-manager' 
    spec:
      project: default
      source:
        path: ''
        repoURL: 'https://charts.jetstack.io'
        targetRevision: v1.15.0
        chart: cert-manager
        helm:
          valuesObject:
            crds:
              enabled: true      
      destination:
        server: '{{server}}' 
        namespace: cert-manager 
      syncPolicy: 
        automated:
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
