apiVersion: apps/v1
kind: Deployment
metadata:
  name: team-a-product
  namespace: app-product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - name: product
        image: public.ecr.aws/nginx/nginx:stable-perl
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
        env:
          - name: current_env
            value: team-a
          - name: current_ver
            value: rc0.2