apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: team-a
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: team-a project
  sourceRepos:
  - https://github.com/aws-samples/amazon-eks-multitenancy-with-loft-virtualcluster
  destinations:
  - namespace: '*'
    server: https://vcteam-a.vcluster-vcteam-a:443
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
    
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team-a-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: team-a
  destination:
    server: https://vcteam-a.vcluster-vcteam-a:443
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  source:
    path: 'applications/team-a-application'
    repoURL: 'https://github.com/aws-samples/amazon-eks-multitenancy-with-loft-virtualcluster'
    targetRevision: main