apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyverno:create-update-secrets
  labels:
    rbac.kyverno.io/aggregate-to-background-controller: "true"  
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyverno:list-get-secrets
  labels:
    rbac.kyverno.io/aggregate-to-admission-controller: "true"  
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - get   
  - list  
  - watch
